title                    : "Ujjal Timshina"
title_separator          : "-"
name                     : "Ujjal Timshina"
description              : "PhD Scholar, School of Mathematics"
url                      : "https://ujjalt.github.io/ujjaltimshina"
baseurl                  : ""
repository               : "ujjalt/ujjaltimshina"

author:
  avatar: "images/IMG_1458.png"
  name: "Ujjal Timshina"
  bio: "Doctoral Researcher, School of Mathematics, IIIT Delhi"
  email: "ujjalt@iiitd.ac.in"
  github: "ujjaltimshina"
  facebook: "Ujjal Timshina"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima  # Or use remote_theme: "mmistakes/minimal-mistakes@4.24.0"
