# Basic Site Settings
title: "Ujjal Timshina"
title_separator: "-"
name: &name "Ujjal Timshina"
description: &description "PhD Scholar, School of Mathematics"
url: "https://timshinaujjal.github.io"   # Your live URL
baseurl: ""                             # Keep empty for root domain
repository: "timshinaujjal.github.io" # GitHub repo

# Theme (Minimal Mistakes)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
  - jekyll-remote-theme

# Whitelist plugins (fix typo)
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji

# Author info for sidebar
author:
  avatar: "images/IMG_1458.png"  # Adjust path to your avatar image
  name: "Ujjal Timshina"
  bio: "Doctoral Researcher, School of Mathematics, IIIT Delhi"
  location: "New Delhi, India"
  employer: "IIIT, Delhi"
  email: "ujjalt@iiitd.ac.in"

  # Social media links you want to show
  github: "ujjaltimshina"
  facebook: "Ujjal Timshina"
  instagram: ""    # Add your Instagram username if any
  uri: "https://timshinaujjal.github.io"  # Your website URL

# Defaults to enable author_profile on pages/posts etc.
defaults:
  - scope:
      path: ""
    values:
      custom_css: style.css   # If you add custom CSS
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Disable footer GitHub and feed links:
footer:
  show_github: false
  show_feed: false

# Site settings
permalink: /:categories/:title/
timezone: Etc/UTC

# Markdown & Syntax highlighting
markdown: kramdown
highlighter: rouge

# Sass settings (if you use Sass)
sass:
  sass_dir: _sass
  style: compressed

# Exclude from build
exclude:
  - "node_modules"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"

# Include extra files
include:
  - ".htaccess"
  - "_pages"
  - "files"

# Analytics (disabled)
analytics:
  provider: false
